---
- name: Deploy a RHEL VM on Proxmox
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    api_user: "awx@pve"
    api_password: "baraka2025"
    api_host: "192.168.1.56"
    node: "pve"
    vmid: "{{ lookup('ansible.builtin.sequence', 'start=900 end=999 count=1', wantlist=True) | first }}"
    vm_name: "{{ vm_name | default('rhel-test') }}"
    vm_memory: "{{ vm_memory | default(4096) }}"
    vm_disk: "{{ vm_disk | default(50) }}"
    iso_path: "{{ iso_path | default('local:iso/rhel-9.6-x86_64-dvd.iso') }}"
    os_type: "{{ os_type | default('rhel9') }}"
    storage: "{{ storage | default('local-lvm') }}"
    net_bridge: "{{ net_bridge | default('vmbr0') }}"

  tasks:
    - name: Create VM on Proxmox
      community.proxmox.proxmox_kvm:
        api_user: "{{ api_user }}"
        api_password: "{{ api_password }}"
        api_host: "{{ api_host }}"
        node: "{{ node }}"
        vmid: "{{ vmid }}"
        name: "{{ vm_name }}"
        memory: "{{ vm_memory }}"
        cores: 2
        sockets: 1
        scsihw: virtio-scsi-pci
        sata0: "{{ storage }}:{{ vm_disk }}"
        net0: virtio,bridge={{ net_bridge }}
        ide2: "{{ iso_path }},media=cdrom"
        bootdisk: sata0
        ostype: l26
        onboot: true
        state: present
      delegate_to: localhost

    - name: Start the VM
      community.proxmox.proxmox_kvm:
        api_user: "{{ api_user }}"
        api_password: "{{ api_password }}"
        api_host: "{{ api_host }}"
        vmid: "{{ vmid }}"
        state: started
      delegate_to: localhost

