---
- name: Création VM RHEL 9.6 sur Proxmox - vm2-kibana
  hosts: "{{ proxmox_host | default('192.168.1.56') }}"
  gather_facts: no
  become: yes

  vars:
    vm_id: 312
    vm_name: vm2-kibana
    vm_memory: 8192
    vm_cores: 4
    vm_disk_size: 50
    vm_storage: local-lvm
    iso_storage: local
    iso_file: rhel-9.6-x86_64-dvd.iso
    bridge: vmbr0

  tasks:
    - name: Arrêter VM {{ vm_id }} si elle existe
      command: qm stop {{ vm_id }}
      register: stop_result
      failed_when: false
      changed_when: stop_result.rc == 0

    - name: Attendre l'arrêt complet de la VM
      pause:
        seconds: 5
      when: stop_result.rc == 0

    - name: Supprimer VM {{ vm_id }} si existante
      command: qm destroy {{ vm_id }} --purge
      register: destroy_result
      failed_when: false
      changed_when: destroy_result.rc == 0

    - name: Créer VM {{ vm_name }} (ID {{ vm_id }})
      command: >
        qm create {{ vm_id }}
        --name {{ vm_name }}
        --memory {{ vm_memory }}
        --cores {{ vm_cores }}
        --cpu host
        --sockets 1
        --ostype l26
        --machine q35
        --bios ovmf
        --scsihw virtio-scsi-pci
        --scsi0 {{ vm_storage }}:{{ vm_disk_size }},format=raw
        --efidisk0 {{ vm_storage }}:1,format=raw,efitype=4m,pre-enrolled-keys=1
        --ide2 {{ iso_storage }}:iso/{{ iso_file }},media=cdrom
        --net0 virtio,bridge={{ bridge }}
        --boot order=ide2;scsi0
        --bootdisk scsi0
        --vga std
        --serial0 socket
        --agent enabled=1
        --onboot 1
      register: create_result

    - name: Démarrer la VM pour installation
      command: qm start {{ vm_id }}

    - name: Message d'information
      debug:
        msg: "VM {{ vm_name }} créée et démarrée"
