---
- name: Installation automatique RHEL 9.6 avec Kickstart
  hosts: "{{ proxmox_host | default('192.168.1.56') }}"
  gather_facts: yes
  become: yes

  vars:
    vm_id: "{{ vm_id }}"
    vm_name: "{{ vm_name }}"
    vm_memory: 4096
    vm_cores: 2
    vm_disk_size: 80
    vm_storage: local-lvm
    iso_storage: local
    iso_file: rhel-9.6-x86_64-dvd.iso
    bridge: vmbr0
    kickstart_port: 8088

  tasks:
    - name: Créer dossier kickstart
      file:
        path: /var/www/kickstart
        state: directory
        mode: '0755'

    - name: Copier fichier kickstart
      copy:
        src: ../rhel96-kickstart.cfg
        dest: /var/www/kickstart/ks.cfg
        mode: '0644'

    - name: Arrêter ancien serveur web si existe
      shell: pkill -f "python3 -m http.server {{ kickstart_port }}"
      ignore_errors: yes

    - name: Attendre arrêt serveur web
      pause:
        seconds: 2

    - name: Démarrer serveur web kickstart
      shell: cd /var/www/kickstart && nohup python3 -m http.server {{ kickstart_port }} >/dev/null 2>&1 &
      async: 5
      poll: 0

    - name: Attendre démarrage serveur web
      wait_for:
        port: "{{ kickstart_port }}"
        delay: 3
        timeout: 15

    - name: Tester URL kickstart
      uri:
        url: "http://{{ ansible_default_ipv4.address }}:{{ kickstart_port }}/ks.cfg"
        return_content: no
        status_code: 200

    - name: Arrêter VM si existe
      command: qm stop {{ vm_id }}
      failed_when: false

    - name: Attendre arrêt
      pause:
        seconds: 3

    - name: Supprimer VM si existe
      command: qm destroy {{ vm_id }} --purge
      failed_when: false

    - name: Créer VM avec kickstart
      command: >
        qm create {{ vm_id }}
        --name {{ vm_name }}
        --memory {{ vm_memory }}
        --cores {{ vm_cores }}
        --cpu host
        --sockets 1
        --ostype l26
        --machine q35
        --bios ovmf
        --scsihw virtio-scsi-pci
        --scsi0 {{ vm_storage }}:{{ vm_disk_size }},format=raw
        --efidisk0 {{ vm_storage }}:1,format=raw,efitype=4m,pre-enrolled-keys=1
        --ide2 {{ iso_storage }}:iso/{{ iso_file }},media=cdrom
        --net0 virtio,bridge={{ bridge }}
        --boot order=ide2
        --vga std
        --serial0 socket
        --agent enabled=1
        --onboot 1

    - name: Démarrer la VM
      command: qm start {{ vm_id }}

    - name: Attendre démarrage VM
      pause:
        seconds: 5

    - name: Instructions boot manuel
      debug:
        msg: |
          ==========================================
          VM {{ vm_name }} créée et démarrée !
          
          ⚠️ ACTION MANUELLE REQUISE (1 seule fois) :
          
          1. Allez sur Proxmox Console → VM {{ vm_id }}
          2. Au menu de boot RHEL, appuyez sur 'e' (éditer)
          3. Trouvez la ligne 'linuxefi' ou 'linux'
          4. Ajoutez à la fin de cette ligne :
             inst.ks=http://{{ ansible_default_ipv4.address }}:{{ kickstart_port }}/ks.cfg
          5. Appuyez sur Ctrl+X pour booter
          
          Ensuite l'installation sera 100% automatique !
          Durée : 10-15 minutes
          
          Credentials après installation :
          - root / baraka
          - baraka / baraka (avec sudo)
          
          URL Kickstart : http://{{ ansible_default_ipv4.address }}:{{ kickstart_port }}/ks.cfg
          ==========================================
